"""Paper table for the v8 overnight batch (scripts/box_v8.sh).

Reads whatever finished and reports it. Two blocks carry the paper:

* **The attribution experiment.** Every pre-2026-07-26 result came from a corpus
  where the source object was detected on 0.0% of frames AND from a different
  architecture, so it could never separate perception from design. The blind
  control differs from the main arm in exactly one thing — object evidence — so
  their gap is attributable.
* **Seed spread.** paper.md 4m measured an 11.1x fold in `std_ratio` across
  runs of one identical config. Any arm gap smaller than the seed sd is not a
  result, and this prints the sd next to the gaps so that cannot be forgotten.
"""
from __future__ import annotations

import glob
import json
import os
import re
import statistics as st

ARMS = [
    ("v8_s0", "v8, sighted (main)"),
    ("v8_blind", "v8, BLIND control"),
    ("v8_s1", "v8, seed 1"),
    ("v8_s2", "v8, seed 2"),
    ("v7_arch", "v7 architecture, sighted"),
    ("v8_norel", "v8, no relational"),
]


def bench(tag: str) -> dict:
    f = f"eval_results/bench_{tag}.json"
    if not os.path.exists(f):
        return {}
    try:
        return json.load(open(f)).get("aggregate", {})
    except Exception:
        return {}


def closed_loop(tag: str) -> list[float]:
    """mean_success per suite for one arm."""
    out = []
    for f in sorted(glob.glob(f"logs/box_v8/cl_{tag}_*.log")):
        try:
            m = re.search(r'"mean_success":\s*([0-9.]+)', open(f, errors="ignore").read())
        except OSError:
            continue
        if m:
            out.append(float(m.group(1)))
    return out


def fmt(a: dict, key: str, n: int = 3) -> str:
    v = a.get(key)
    return f"{v:.{n}f}" if isinstance(v, (int, float)) and v == v else "—"


def main() -> None:
    rows = {tag: (bench(tag), closed_loop(tag)) for tag, _ in ARMS}

    print("# MicroVLA v8 — overnight results\n")
    print("Generated by `scripts/box_v8.sh`. Arms that did not finish show `—`.\n")
    print("| arm | closed-loop success | std_ratio | wp_std_ratio | corr | grip | "
          "pose_mae | wm_margin |")
    print("|---|---|---|---|---|---|---|---|")
    for tag, label in ARMS:
        a, s = rows[tag]
        succ = f"**{st.mean(s):.3f}** ({len(s)} suite{'s' if len(s) != 1 else ''})" if s else "—"
        wm = a.get("wm_margin_pct")
        wm_s = f"{wm:.1f}%" if isinstance(wm, (int, float)) else "—"
        print(f"| {label} | {succ} | {fmt(a,'std_ratio')} | {fmt(a,'wp_std_ratio')} | "
              f"{fmt(a,'corr',2)} | {fmt(a,'grip_acc',2)} | {fmt(a,'pose_mae')} | {wm_s} |")

    # ---- seed spread first: it sets the bar every other gap must clear -------
    seeds = {t: rows[t][0].get("std_ratio") for t in ("v8_s0", "v8_s1", "v8_s2")
             if isinstance(rows[t][0].get("std_ratio"), (int, float))}
    sd = None
    print("\n## Seed spread — the bar every comparison must clear\n")
    if len(seeds) >= 2:
        v = list(seeds.values())
        sd = st.stdev(v) if len(v) > 1 else 0.0
        print(f"`std_ratio` over {len(v)} seeds: mean **{st.mean(v):.3f}**, sd **{sd:.3f}**, "
              f"range {min(v):.3f}–{max(v):.3f}\n")
        print(f"`{seeds}`\n")
        print("These arms share one stage A and differ only in the stage-B seed, so this")
        print("is a POLICY-level error bar and understates full run-to-run variance")
        print("(paper.md 4m measured an 11.1x fold end to end). **Any arm gap smaller")
        print("than this sd is not a result.**")
    else:
        print(f"Only {len(seeds)} seed finished — no error bar, so no arm comparison")
        print("below is interpretable as a result.")

    # ---- the attribution experiment -----------------------------------------
    print("\n## The attribution experiment: does perception explain it?\n")
    sa, ss = rows["v8_s0"]
    ba, bs = rows["v8_blind"]
    if sa and ba:
        print("Identical architecture, identical frames and actions. The blind corpus has")
        print("its object evidence zeroed and centers pinned to the fallback — the exact")
        print("state EVERY corpus this project trained on was in before 2026-07-26")
        print("(paper.md 4n). The two differ in one variable, so the gap is attributable.\n")
        print("| metric | sighted | blind | delta | > seed sd? |")
        print("|---|---|---|---|---|")
        for key, n in (("std_ratio", 3), ("corr", 2), ("grip_acc", 2), ("pose_mae", 3)):
            x, y = sa.get(key), ba.get(key)
            if isinstance(x, (int, float)) and isinstance(y, (int, float)):
                d = x - y
                verdict = "—" if sd is None else ("yes" if abs(d) > sd else "**no**")
                print(f"| {key} | {x:.{n}f} | {y:.{n}f} | {d:+.{n}f} | {verdict} |")
        if ss and bs:
            print(f"| closed-loop success | {st.mean(ss):.3f} | {st.mean(bs):.3f} | "
                  f"{st.mean(ss) - st.mean(bs):+.3f} | — |")
        else:
            print("\nClosed-loop numbers missing for one side — the pair that matters most.")
    else:
        print("Not available: the main arm or its blind control did not finish.")

    # ---- design ablations ---------------------------------------------------
    print("\n## Design ablations\n")
    print("| comparison | what it isolates |")
    print("|---|---|")
    print("| `v8, sighted` vs `v7 architecture, sighted` | HRM + relational head + "
          "TRM-before-relational ordering, holding the corpus fixed |")
    print("| `v8, sighted` vs `v8, no relational` | the relational head alone, holding "
          "the world model fixed (same stage A) |")
    print("| `v8, sighted` vs `v8, BLIND control` | object evidence alone, holding "
          "architecture fixed |")
    print("\nRead each against the seed sd above before calling it an effect.")


if __name__ == "__main__":
    main()
